### ISSUE TITLE
PydanticOmit failing with duplicated union field

### ISSUE THREAD

**Issue by ericliuche** [pydantic/pydantic#11553]
### Initial Checks

- [x] I confirm that I'm using Pydantic V2

### Description

When using a custom type that omits its JSON schema (by raising `PydanticOmit` in its `__get_pydantic_json_schema__` method), the schema generation behaves inconsistently. In a model with a single field of a union type, the JSON schema is generated successfully (omitting the custom type as intended). However, when the same custom type is used in multiple fields within one model, generating the JSON schema fails with a `PydanticOmit` exception.

### Example Code

```Python
from pydantic_core import PydanticOmit
from pydantic import BaseModel

class CustomSerializedType(BaseModel):
    @classmethod
    def __get_pydantic_json_schema__(
        cls, core_schema, handler,
    ) -> JsonSchemaValue:
        raise PydanticOmit

class SingleField(BaseModel):
    first_field: list[float | CustomSerializedType]

class DuplicatedField(BaseModel):
    first_field: list[float | CustomSerializedType]
    second_field: list[float | CustomSerializedType]

# This is fine
SingleField.model_json_schema()
"""
{'properties': {'first_field': {'items': {'type': 'number'},
   'title': 'First Field',
   'type': 'array'}},
 'required': ['first_field'],
 'title': 'SingleField',
 'type': 'object'}
"""

# This raises an error
DuplicatedField.model_json_schema()
"""
...
handler_func(schema_or_field, current_handler, js_modify_function)
    535 def new_handler_func(
    536     schema_or_field: CoreSchemaOrField,
    537     current_handler: GetJsonSchemaHandler = current_handler,
    538     js_modify_function: GetJsonSchemaFunction = js_modify_function,
    539 ) -> JsonSchemaValue:
--> 540     json_schema = js_modify_function(schema_or_field, current_handler)
    541     if _core_utils.is_core_schema(schema_or_field):
    542         json_schema = populate_defs(schema_or_field, json_schema)

Cell In[20], line 9, in CustomSerializedType.__get_pydantic_json_schema__(cls, core_schema, handler)
      5 @classmethod
      6 def __get_pydantic_json_schema__(
      7     cls, core_schema, handler,
      8 ) -> JsonSchemaValue:
----> 9     raise PydanticOmit

PydanticOmit: PydanticOmit()
"""
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.6
        pydantic-core version: 2.27.2
          pydantic-core build: profile=release pgo=false
                 install path: .venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.7 (main, Oct 16 2024, 07:12:08) [Clang 18.1.8 ]
                     platform: macOS-15.2-arm64-arm-64bit
             related packages: fastapi-0.115.6 mypy-1.15.0 pydantic-settings-2.6.1 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by ericliuche** [comment]
@Viicos Am I doing this right? It seems the SkipJsonSchema is still causing a failure:
```
from pydantic_core import PydanticOmit
from pydantic import BaseModel
from pydantic.json_schema import SkipJsonSchema

class CustomSerializedType(BaseModel):
    @classmethod
    def __get_pydantic_json_schema__(
        cls, core_schema, handler,
    ) -> JsonSchemaValue:
        raise PydanticOmit

class DuplicatedField(BaseModel):
    first_field: list[float | SkipJsonSchema[CustomSerializedType]]
    second_field: list[float | SkipJsonSchema[CustomSerializedType]]

DuplicatedField.model_json_schema()
```
```
...
Cell In[34], line 10, in CustomSerializedType.__get_pydantic_json_schema__(cls, core_schema, handler)
      6 @classmethod
      7 def __get_pydantic_json_schema__(
      8     cls, core_schema, handler,
      9 ) -> JsonSchemaValue:
---> 10     raise PydanticOmit

PydanticOmit: PydanticOmit()
```

**Comment by Viicos** [comment]
You need to remove the custom `CustomSerializedType.__get_pydantic_json_schema__()` implementation.

**Comment by ericliuche** [comment]
The issue there is I do in fact need custom serialization logic in my model, where sometimes I need to skip a field completely. Is there any other way around this @Viicos? Really appreciate the help!

**Comment by Viicos** [comment]
Doing `SkipJsonSchema[CustomSerializedType]` is equivalent to doing `Annotated[CustomSerializedType, SkipJsonSchema()]`, with `SkipJsonSchema` implemented as:

```python
class SkipJsonSchema:
        def __get_pydantic_json_schema__(
            self, core_schema: CoreSchema, handler: GetJsonSchemaHandler
        ) -> JsonSchemaValue:
            raise PydanticOmit
```

So you can have custom serialization logic defined on `CustomSerializedType`, but you need to remove the `CustomSerializedType.__get_pydantic_json_schema__()` implementation as it is already covered by `SkipJsonSchema__get_pydantic_json_schema__()`.

**Comment by ericliuche** [comment]
Ah I should have clarified, my use case of `CustomSerializedType` isn't just a `raise PydanticOmit`. It depends on the attributes whether or not it should be skipped or not, e.g.

```python
class CustomSerializedType[T](BaseModel):

    @classmethod
    def __get_pydantic_json_schema__(
        cls, core_schema, handler,
    ):
        t_args = pydantic_get_args(cls)
        if t_args[0] == int:
            raise PydanticOmit
       # continue on to do some other stuff
```

**Comment by ericliuche** [comment]
@Viicos following up on this, do you have any suggestions for how to handle the conditional `PydanticOmit` with the duplicate definitions? thanks again

**Comment by Viicos** [comment]
@ericliuche sorry for the delay.

It is a bit unfortunate because the `__get_pydantic_json_schema__()` is a bit different than `__get_pydantic_core_schema__()`, where even if defined on an annotated class, you can still access the annotated class:

```python
class MyAnn:
    @classmethod
    def __get_pydantic_core_schema__(cls, source, handler):
        t_args = pydantic_get_args(source)
        ...

class Model(BaseModel):
    a: Annotated[MyGenericModel[int], MyAnn]
```

And this isn't possible with `__get_pydantic_json_schema__()`. A workaround (although a bit more complex) could be to do the following:

```python
from typing import Annotated

from pydantic_core import CoreSchema

from pydantic import BaseModel, GetJsonSchemaHandler
from pydantic.json_schema import JsonSchemaValue, PydanticOmit


class CustomSerializedType[T](BaseModel):
    a: T


class CustomSkipJsonSchema:
    def __class_getitem__(cls, item):
        return Annotated[item, cls()]

    def __get_pydantic_json_schema__(
        self, core_schema: CoreSchema, handler: GetJsonSchemaHandler
    ) -> JsonSchemaValue:
        schema = handler.resolve_ref_schema(handler(core_schema))
        if schema['properties']['a']['type'] == 'integer':
            raise PydanticOmit
        return schema



class DuplicatedField(BaseModel):
    first_field: list[float | CustomSkipJsonSchema[CustomSerializedType[int]]]
    second_field: list[float | CustomSkipJsonSchema[CustomSerializedType[int]]]
```

It's less ideal because you have to rely on a specific field of the JSON Schema. The `core_schema` is the one for `CustomSerializedType`, and so we could access the `cls` item from it (and then do the same logic as you did using `get_args()`) but because `CustomSerializedType` is being referenced twice, `core_schema` is actually a [`'definition-reference'`](https://docs.pydantic.dev/latest/api/pydantic_core_schema/#pydantic_core.core_schema.definition_reference_schema) schema.

To be clear, this is just a workaround and the issue you reported should be fixed at some point.

**Comment by ericliuche** [comment]
@Viicos really appreciate the follow up! I'm still struggling a bit trying to get this to work with my actual use case which looks like this

```py
from pydantic._internal._generics import get_args as pydantic_get_args
from pydantic._internal._generics import get_origin as pydantic_get_origin
from pydantic import BaseModel
from pydantic_core import PydanticOmit, core_schema

class Mention[T](BaseModel):
    @classmethod
    def __get_pydantic_json_schema__(
        cls, core_schema: core_schema.CoreSchema, handler: GetJsonSchemaHandler
    ) -> JsonSchemaValue:

        t_args = pydantic_get_args(cls)
       
        # context here is a mapping of types to list of field names to override the type with, e.g.
        # e.g.
        # context = {int: ["my_int"]}
        context = get_mention_types_context()

        for context_type, field_names in context.items():
            if t_type == context_type:
                return {
                    "type": "string",
                    "enum": field_names,
                }

        raise PydanticOmit
```
so it can be used like
```py
class MyClass(BaseModel):
    mention_or_int: int | Mention[int]
    mention_or_str: str | Mention[str]

with set_mention_types_context({int: ["my_int"], str: ["my_str"]}):
    MyClass.model_json_schema()
```

**Comment by Viicos** [comment]
If the `T` type variable isn't reflected in any way in fields (so that you can leverage it as I did in my `CustomSkipJsonSchema` implementation), then I don't have a suitable workaround for you, sorry about that.

**Comment by ericliuche** [comment]
@Viicos Ah I see. I guess I could add it as an unused placeholder value. Though in that case, would it be possible to get the native python type instead of the stringified schema type (e.g. in your example`schema['properties']['a']['type'] == 'integer'`)?

Ideally I would be able to make my type comparisons like `== int` instead of `== 'integer'`

**Comment by Viicos** [comment]
A very ugly workaround would be to do:

```python
from typing import Annotated

from pydantic_core import CoreSchema

from pydantic import BaseModel, GetJsonSchemaHandler
from pydantic.json_schema import JsonSchemaValue, PydanticOmit

class CustomSkipJsonSchema:
    def __class_getitem__(cls, item):
        return Annotated[item, cls()]

    def __get_pydantic_json_schema__(
        self, core_schema: CoreSchema, handler: GetJsonSchemaHandler
    ) -> JsonSchemaValue:
        schema = handler.resolve_ref_schema(handler(core_schema))
        if schema == {'omit': True}:
            raise PydanticOmit
        return schema


def get_mention_types_context():
    return {int: ["my_int"]}


class Mention[T](BaseModel):
    @classmethod
    def __get_pydantic_json_schema__(
        cls, schema: CoreSchema, handler: GetJsonSchemaHandler
    )  -> JsonSchemaValue:
        args = cls.__pydantic_generic_metadata__['args']
        t_type = args[0]

        context = get_mention_types_context()

        for context_type, field_names in context.items():
            if t_type == context_type:
                return {
                    "type": "string",
                    "enum": field_names,
                }

        return {'omit': True}


class DuplicatedField(BaseModel):
    first_field: list[float | CustomSkipJsonSchema[Mention[int]]]
    second_field: list[float | CustomSkipJsonSchema[Mention[str]]]
```

But you will have to make sure that `CustomSkipJsonSchema` is always used with `Mention`.

**Comment by ericliuche** [comment]
@Viicos sweet! despite the ugliness I think that fixed it :)

this ended up working for me, i renamed `Mention` to `_Mention` and added this helper type
```py
_SKIP_SCHEMA = CustomSkipJsonSchema()

type Mention[T] = Annotated[_Mention[T], _SKIP_SCHEMA]
```

**Comment by AhsanSheraz** [comment]
Fixed in https://github.com/pydantic/pydantic/pull/12921

The root cause was that `definitions_schema()` in `json_schema.py` catches `PydanticInvalidForJsonSchema` when processing definitions but had no handler for `PydanticOmit`. When a type raising `PydanticOmit` is used in only one field, it works fine (no definitions entry created). But when the same type appears in multiple fields, pydantic-core deduplicates it into a shared definition, and the unhandled `PydanticOmit` propagated as an unhandled exception.

The fix follows the same pattern already established for `PydanticInvalidForJsonSchema`:

1. Catch `PydanticOmit` in `definitions_schema()` and record the definition ref in a tracking set
2. Re-raise `PydanticOmit` in `definition_ref_schema()` when the referenced definition was omitted, so the calling context (`union_schema`, `_named_required_fields_schema`, etc.) can handle it normally
3. Propagate through `get_schema_from_definitions()` and `_add_json_refs()` for consistency

This also fixes the `SkipJsonSchema[CustomModel]` workaround that was failing with duplicate fields, and the conditional `PydanticOmit` case mentioned in the comments.

**Comment by MLuc24** [comment]
Still reproduces on `main` (2.14.0b1, `pydantic-core` 2.48.0) — the single-field case is fine and the duplicated one raises:

```
single : {"properties": {"first_field": {"items": {"type": "number"}, ...}}, ...}
dup    : RAISED PydanticOmit PydanticOmit()
```

I traced it before reading the thread and landed on the same place @AhsanSheraz described, so for the record, with line numbers on current `main`:

`definitions_schema` walks the definitions and catches exactly one exception type:

```python
# json_schema.py:2211
for definition in schema['definitions']:
    try:
        self.generate_inner(definition)
    except PydanticInvalidForJsonSchema as e:
        core_ref: CoreRef = CoreRef(definition['ref'])
        self._core_defs_invalid_for_json_schema[self.get_defs_ref((core_ref, self.mode))] = e
        continue
```

There is no `except PydanticOmit`, so once a type is referenced twice and pydantic-core hoists it into `definitions`, the omit escapes `model_json_schema()` entirely. With one reference there is no definitions entry, the omit is raised inside the union instead, and the existing handler at `union_schema` (line 1340) drops that member — which is why the two cases diverge.

What makes me think this is tractable rather than open-ended is that the machinery for "this definition could not be generated" already exists and is symmetric: `_core_defs_invalid_for_json_schema` is declared at 307, populated at 2216, cleared at 480, and **re-raised at the two ref-resolution points**, 2439 and 2551. An omit needs the same three moves — record the ref, then re-raise `PydanticOmit` where the ref is resolved — after which the handlers that already exist at 1340, 1409 and 1590 do the work unchanged. That is roughly fifteen lines mirroring code that is already there, not a new mechanism.

I am aware you closed #12921, and I do not want to walk into the same wall, so before writing anything: was the approach itself wrong, or was it the shape of that PR? It came in at +168/-3 with 81% coverage on the added lines, which is a lot for what the symmetry above suggests, and I could see either being the objection.

If the approach is acceptable, **could this be assigned to me?** I would keep it to the parallel of the existing invalid-defs handling, with tests covering the duplicated-union case from the report, `SkipJsonSchema[SomeModel]` used twice, and the conditional-omit case @ericliuche raised. If you would rather leave it alone given your "isn't easily fixable" note, that is a perfectly good answer too and I will drop it — I would just rather ask than spend a day guessing.

**Comment by lovettsendit** [comment]
I reproduced this on current main and have a tested fix ready, including regression coverage for nested and dependent definitions. Please assign this issue to me so I can open the pull request.

https://github.com/lovettsendit/pydantic/tree/fix/omit-json-schema-definitions
