### ISSUE TITLE
`Field` metadata from `Annotated` is lost after a call to `update_forward_refs`

### ISSUE THREAD

**Issue by xx55tt** [pydantic/pydantic#3282]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: False
                 install path: /usr/lib/python3.9/site-packages/pydantic
               python version: 3.9.7 (default, Aug 31 2021, 13:28:12)  [GCC 11.1.0]
                     platform: Linux-5.14.8-arch1-1-x86_64-with-glibc2.33
     optional deps. installed: ['email-validator', 'typing-extensions']
```
```py
from __future__ import annotations
from typing import Annotated

from pydantic import BaseModel, Field


class Works(BaseModel):
    foo: list[Foo] = Field(..., alias="bar")


class Fails(BaseModel):
    foo: Annotated[list[Foo], Field(alias="bar")]


class Foo(BaseModel):
    a: int


Works.update_forward_refs()
Fails.update_forward_refs()

json = '{"bar":[{"a":0}]}'

Works.parse_raw(json)
Fails.parse_raw(json)
```
With the postponed evaluation of annotations enabled, the `Field` metadata seems to be lost after the `update_forward_refs` call. Apart from that it seemed to be working fine, it parsed the JSON if the field name was `foo`. I also tried the `allow_mutation` argument, it was not working as well.

Without the `from __future__ import annotations` import, all of the following worked:
```py
foo: "list[Foo]" = Field(..., alias="bar")
foo: List["Foo"] = Field(..., alias="bar")
foo: list[ForwardRef("Foo")] = Field(..., alias="bar")
foo: Annotated["list[Foo]", Field(alias="bar")]
foo: Annotated[List["Foo"], Field(alias="bar")]
foo: Annotated[list[ForwardRef("Foo")], Field(alias="bar")]
```

**Comment by dmontagu** [comment]
It looks like this is now fixed in both v1 and v2

**Comment by mshonichev** [comment]
Whoa! Why was this issue closed without merging the fix? 
I find it is still reproducing at 
```
pydantic==2.3.0
pydantic_core==2.6.3
```

reproducer is exactly the same:
```
from __future__ import annotations

class Foo(BaseModel):
    bar: Annotated[Bar | None, Field(alias="_bar")] = None

class Bar(BaseModel):
    foo: int | None = None


def test_model():
    data= '{"_bar": {"foo": 42}}'
    model = Foo.model_validate_json(data)
    assert model.bar.foo == 42
```

throws `AttributeError: 'NoneType' object has no attribute 'foo'`

but if we change the order of declarations, validation successfully loads the alias and test succeeds:

```

class Bar(BaseModel):
    foo: int | None = None

class Foo(BaseModel):
    bar: Annotated[Bar | None, Field(alias="_bar")] = None


def test_model():
    data= '{"_bar": {"foo": 42}}'
    model = Foo.model_validate_json(data)
    assert model.bar.foo == 42
```

**Comment by mshonichev** [comment]
@dmontagu could you please reopen this issue, or should I probably file a new one?

**Comment by dmontagu** [comment]
I'm not sure why I closed it, clearly it's still an issue. Apologies for that.

**Comment by dmontagu** [comment]
I think I've got a fix for it ready in #7698 (at least for pydantic v2), thanks for bringing this to my attention again, and apologies for closing it before when it wasn't actually fixed.

**Comment by dmontagu** [comment]
Also @mshonichev, I added a different test in #7698, but I can confirm that your snippet above does not error with the change in that PR.

**Comment by AntonOvsyannikov** [comment]
Hello. Just reproduced with pydantic 1.10.18 and 2.9.2 (v1 mode)

```
from __future__ import annotations

from typing import Annotated

from pydantic.v1 import BaseModel, Field


class Foo(BaseModel):
    bar1: "Bar" = Field(extra=True)
    bar2: Annotated["Bar", Field(extra=True)]


class Bar(BaseModel):
    ...


Foo.update_forward_refs()

print(Foo.__fields__["bar1"].field_info.extra)  # {'extra': True}
print(Foo.__fields__["bar2"].field_info.extra)  # {}

```

With no `from __future__ import annotations` works well.
