### ISSUE TITLE
Layout conflict in ModelMetaclass when mixing in two models with private variables.

### ISSUE THREAD

**Issue by igoras1993** [pydantic/pydantic#3523]
# Bug
Disclaimer: I have checked out stackoverflow, issue tracker, docs, google etc. for resources on this, but didnt found any solution. 

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /home/igor/code/issues-reports/pydantic-private-mixins/venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.9 (main, Nov 16 2021, 03:08:02)  [GCC 9.3.0]
                     platform: Linux-5.11.0-34-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']

```

Following code looks innocent, It just uses mixin models to merge some private attributes in one bigger model:

```py
import pydantic
import typing as t


class ModelMixin(pydantic.BaseModel):
    _mixin_private: t.Optional[str] = pydantic.PrivateAttr(None)


class Model(pydantic.BaseModel):
    public: str = "default"
    _private: t.Optional[str] = pydantic.PrivateAttr(None)


class NewModel(ModelMixin, Model):
    pass

```
But quite surprisingly it raises a `TypeError` on a class creation time:

```
Traceback (most recent call last):
  File "/code/issues-reports/pydantic-private-mixins/report.py", line 14, in <module>
    class NewModel(ModelMixin, Model):
  File "pydantic/main.py", line 367, in pydantic.main.ModelMetaclass.__new__
  File "/usr/lib/python3.9/abc.py", line 106, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
TypeError: multiple bases have instance lay-out conflict
```
It seems that **at least two** models with private attributes will trigger this exception. When private attributes are defined in only one of the models, everything works great. 

I can dig into this, but probably not this week. But please confirm that this is an issue, not the intended behavior. Also, if You have any ideas/hints where to start, it would be appreciated!

**Comment by igoras1993** [comment]
Okay, some update. 
It seems like problem with `__slots__` and multiple inheritance. Pydantic's documentation states directly, that creating a private attribute will also create a `__slots__` entry:
> [Upon class creation pydantic constructs __slots__ filled with private attributes.](https://pydantic-docs.helpmanual.io/usage/models/#private-model-attributes)

This behaviour can be confirmed when inspecting metaclass runtime details for all three models from my code example:

```
ModelMixin:
    Bases + mro:
        (<class 'pydantic.main.BaseModel'>, <class 'pydantic.utils.Representation'>, <class 'object'>)

    Namespace:
{       '__annotations__': {'_mixin_private': typing.Optional[str]},
        '__class_vars__': set(),
        '__config__': <class '__main__.Config'>,
        '__custom_root_type__': False,
        '__fields__': {},
        '__hash__': None,
        '__json_encoder__': <staticmethod object at 0x7f9745885460>,
        '__module__': '__main__',
        '__post_root_validators__': [],
        '__pre_root_validators__': [],
        '__private_attributes__': {'_mixin_private': ModelPrivateAttr()},
        '__qualname__': 'ModelMixin',
        '__schema_cache__': {},
        '__slots__': {'_mixin_private'},
        '__validators__': {}}

Model:
    Bases + mro:
        (<class 'pydantic.main.BaseModel'>, <class 'pydantic.utils.Representation'>, <class 'object'>)

    Namespace:
{       '__annotations__': {       '_private': typing.Optional[str],
                                   'public': <class 'str'>},
        '__class_vars__': set(),
        '__config__': <class '__main__.Config'>,
        '__custom_root_type__': False,
        '__fields__': {       'public': ModelField(name='public', type=str, required=False, default='default')},
        '__hash__': None,
        '__json_encoder__': <staticmethod object at 0x7f9744f29dc0>,
        '__module__': '__main__',
        '__post_root_validators__': [],
        '__pre_root_validators__': [],
        '__private_attributes__': {'_private': ModelPrivateAttr()},
        '__qualname__': 'Model',
        '__schema_cache__': {},
        '__slots__': {'_private'},
        '__validators__': {}}

NewModel:
    Bases + mro:
        (<class '__main__.ModelMixin'>, <class 'pydantic.main.BaseModel'>, <class 'pydantic.utils.Representation'>, <class 'object'>)
        (<class '__main__.Model'>, <class 'pydantic.main.BaseModel'>, <class 'pydantic.utils.Representation'>, <class 'object'>)

    Namespace:
{       '__class_vars__': set(),
        '__config__': <class '__main__.Config'>,
        '__custom_root_type__': False,
        '__fields__': {       'public': ModelField(name='public', type=str, required=False, default='default')},
        '__hash__': None,
        '__json_encoder__': <staticmethod object at 0x7f9744f29d30>,
        '__module__': '__main__',
        '__post_root_validators__': [],
        '__pre_root_validators__': [],
        '__private_attributes__': {       '_mixin_private': ModelPrivateAttr(),
                                          '_private': ModelPrivateAttr()},
        '__qualname__': 'NewModel',
        '__schema_cache__': {},
        '__slots__': {'_mixin_private', '_private'},
        '__validators__': {}}

```
`ModelMixin` has `'__slots__': {'_mixin_private'}` and `Model` has `'__slots__': {'_private'}`. The child class that derives from both, seems to have slots merged, but I am afraid that this is not enough to convince python interpreter to work. I think that slots should be removed from base classes before calling the `type.__new__()` otherwise it will still fail.

I will post update if I will have something new.

**Comment by igoras1993** [comment]
Okay, I can confirm that this is a problem with `__slot__` and multiple inheritance. There is several solutions, but actualy only one that I personally prefer. The main issue is that **"You cant have conflicting slot definitions on multiple inheritance"**. It is just a dogma at this time.

### 1. Create subclasses of all bases on the fly with slots without private attributes.

This is the most sophisticated solution. Subclassing is required in my opinion. You can't just modify user defined classes directly (at least not in such brutal way). Without subclassing, user defined classes sometimes will have slots with private attrs, sometimes they wont (i.e. they wont always when subclass is used as a base class). 

But subclassing on the fly is even worse. You are introducing highly implicit, not always transparent brick in whole user MRO. It is highly confusing and disgusting solution. In my opinion, it is absolutly anti-pythonic way of doing things, breaking many rules of the zen of python (just as not subclassing).

### 2. Do not create slots at all in pydantic private attrs.

It is okay solution, as long as You do not care about performance and development quality. This minor case of mixing in private attributes would then impact all other pydantic infrastructure. For me, it is step back for a project.  This is still better than 1., but worse than just stating in documentation that mixing in many models with private attributes is just not supported.

### 3. Be explicit: allow user to control slot inserts on any model in config.

For me, it is the best solution. It does not impact usage of pydantic in any way, as long as You state Your demands explicit. It also satisfies the zen of python `Explicit is better than implicit`. It also does not impact runtime performance, it just adds very minor overhead at a class creation time. If user knows that some model is just a mixin and will not be used alone, it **does not** introduce **any** disadvantages. If user wants to use mixin model alone (well, then is should not be named mixin), and still be able to derive from such model, he still can do that, with the cost of using `__dict__` attribute storage instead of `__slot__` (but only when model is used alone). When model is mixed in, the slots are created just normal. Config attribute that controls the behavior of slot inserts should not be inherited from base models (this should be stated directly in docs to inform an user). This way the deriving models will still create slots for all derived private attrs. Not inheriting some very specific config attributes should be okay, since `inherit_config` already is doing some magic merging on  `json_encoders` attribute.
    

Number 3. is the best solution in my opinion. I have already played with it and it seems to work just fine. I have to run pydantic test suite however, just to be sure that it does not brake anything. I can submit PR if You give me some time. It will include:
     
   - New config attribute (e.g. `exclude_private_from_slots`)
   - Special handling of this attribute in `inherit_config`
   - Conditional rendering of the `__slots__` in `ModelMetaclass.__new__`
   - Additional test cases covering this issue
   - Documentation on:
     - New config attribute
     - `PrivateAttr` section update, probably with example

I am not a kind of `mkdocs` guy, never touched it before, so it can take me some time. But please @samuelcolvin review this proposal and tell me if I can work on number 3. solution. If not, tell me how You imagine to solve this issue, and I will try to cover Your needs.

**Comment by igoras1993** [comment]
The test suite runs flawlessly (however master HEAD does not have 100% DC at this time). I have played with this fix in our project, where we are doing some intensive and serious things (including playing with pydantic metaclasses etc.), and I recognized one minor problem to address (actually two, but one is unrelated to this issue, I will open another issue for it). The problem was with `BaseModel.__repr_args__`. It's implementation was assuming that *all keys present in a* `__dict__` *should also be present in a* `__fields__`, which is not true after implementing *no 3.* fix. So the solution that I am proposing will also include `BaseModel.__repr_args__` modification to guard against `KeyError`. 

Waiting for attention, cheers.

**Comment by igoras1993** [comment]
@samuelcolvin Does anybody bothers to reply in this issue? Two months has passed and still no response. As I said, I will submit the PR, but I need to have an agreement on proposed solution. By the time the issue was investigated, I've implemented the feature that fixes it (in my forked branch), and it is working. The only things left to do is to write documentation on new config attribute that this fix introduces. I will write it but actually do not want to do the job that will be rejected, so please, give some feedback.

**Comment by Smlep** [comment]
It seems to have been fixed in https://github.com/samuelcolvin/pydantic/pull/2989

**Comment by zero0nee** [comment]
This issue is not fixed for me in [#2989](https://github.com/samuelcolvin/pydantic/pull/2989) . According to the [changelogs](https://pydantic-docs.helpmanual.io/changelog/) #2989 should be included in v1.9.0a1, but the same bug appears when I run v1.9.0a1, v1.9.0 and v1.9.1. @samuelcolvin @PrettyWood

**Comment by waweber** [comment]
Just chiming in because this issue affects me and possibly other users who want to build models using the mixin pattern.

A workaround I am using involves setting `underscore_attrs_are_private` to make the underscore fields not get transformed into private attributes until the final, mixed model:

```python3
class A(BaseModel):
    a: int = 1
    _privateA: int = 1

class B(BaseModel):
    b: int = 2
    _privateB: int = 2

class AB(B, A):

    class Config:
        underscore_attrs_are_private = True

ab = AB()
print(ab._privateA)
print(ab.dict())
```

This of course will not work for those users who do not wish to use `underscore_attrs_are_private`...

**Comment by peterdudfield** [comment]
me too

**Comment by per11235813** [comment]
me too

**Comment by samuelcolvin** [comment]
We often sort issue by upvote to decide priority, I also actively ignore issues with "me too" comments.

I strongly suggest therefore, that you use the built in feature to register your desire that this gets tackled, not comments.

**Comment by dmontagu** [comment]
Solution proposal: replace the approach of one-slot-per-private-attribute with a new slot called `__pydantic_private__` that will contain a dict with all these things. It will function similarly to `__pydantic_extra__`, and I expect may simplify various implementation details.

I hope to get this out in the coming days.
