### ISSUE TITLE
[PYD-141] PostgresDsn doesn't accept valid socket for host host

### ISSUE THREAD

**Issue by mangecoeur** [pydantic/pydantic#3900]
### Checks

* [x ] I added a descriptive title to this issue
* [ x] I have searched (google, github) for similar issues and couldn't find anything
* [ x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

It is valid to give a unix socket file as a host when connecting to Postgres (e.g. via sqlalchemy) but PostgresDsn throws a 'URL host invalid' error.

```py
from pydantic import BaseSettings, PostgresDsn

class PGSettings(BaseSettings):
    dsn: PostgresDsn = 'postgresql://derp@/databasename?host=/var/run/postgresql'

```

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /opt/conda/envs/geneap-1/lib/python3.9/site-packages/pydantic
               python version: 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:41:03)  [GCC 9.4.0]
                     platform: Linux-5.11.0-36-generic-x86_64-with-glibc2.31
     optional deps. installed: ['dotenv', 'typing-extensions']
```

<sub>[PYD-141](https://linear.app/pydantic/issue/PYD-141/postgresdsn-doesnt-accept-valid-socket-for-host-host)</sub>

**Comment by mangecoeur** [comment]
P.S. Valid format of postgres connection string:

`postgresql://[user[:password]@][netloc][:port][/dbname][?param1=value1&...]`

References

https://stackoverflow.com/questions/27037990/connecting-to-postgres-via-database-url-and-unix-socket-in-rails

https://www.postgresql.org/docs/current/libpq-connect.html

Browsing the code I see that PostgresDsn subclasses AnyUrl, I think it's quite possible to construct a valid Postgres connection string that is not a valid URL.

**Comment by Hajbo** [comment]
I've encountered the same thing a few days ago.
It seems like this issue has been around for a while, see #960

**Comment by wasauce** [comment]
Ran into this due to google cloud. Seems like https://github.com/samuelcolvin/pydantic/issues/960 was closed

Do you think the community would be open to a PR to support a new PostgresDsn -- e.g. GoogleCloudPostgresDsn

**Comment by danizen** [comment]
Yup - just ran into this on https://github.com/danizen/fastapi-bakeoff

**Comment by samuelcolvin** [comment]
My guess would be that this is fixed in v2 she therefore main, PR welcome to add a unit test to check.

**Comment by pgiraud** [comment]
> My guess would be that this is fixed in v2 she therefore main, PR welcome to add a unit test to check.

I would have been happy to add a unit test but unfortunately such a DNS still isn't considered valid.

```
dsn
  Input should be a valid URL, empty host [type=url_parsing, input_value='postgresql://derp@/datab...ost=/var/run/postgresql', input_type=str]
```

**Comment by samuelcolvin** [comment]
Thanks for investigating, looks like this needs to be fixed in pydantic-core, I've created https://github.com/pydantic/pydantic-core/issues/378.

PR welcome to fix that.

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
