### ISSUE TITLE
Pydantic V1 doesn't support mypy V1.1.1

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#5192]
We are aware that Pydantic doesn't support V1.1.1 of mypy. 

This is a tracking progress of fixes for this

Issues so far:
* [x] #5187
* [x] #5190
* [x] #5191

AFAIK v1.0.1 is pretty well supported by pydantic v1.10.6, if you find a problem with v1.0.1 and pydantic, please report it here.

Please don't create more issues about mypy >v1.0.1, instead comment here if you think the above issues don't cover the problem

## Fix timeline

We currently working very hard on pydantic V2 and the significant complexity of pydantic V2 AND the pydantic mypy plugin means that switching back and forth between the two has a significant overhead.

Realistically we won't work on fixing the above for around a month, we will of course try to review community fixes.

My recommendation is to pin `mypy==1.0.1` or earlier.

Partially related, Pydantic V2 will probably support `mypy>=1.2`, and we'll likely add a optional dependency group `pydantic[mypy]` just to constrain mypy, see https://github.com/python/typeshed/pull/9771#issuecomment-1469912090.

**Comment by hatem-goc** [comment]
In https://github.com/pydantic/pydantic/issues/5190 I found that version 1.10.2 of pydantic works well with mypy 1.1.1 YMMV

**Comment by dmontagu** [comment]
I believe all reported issues with using mypy 1.1.1 with pydantic v1 have been resolved, and fixes are included in the 1.10.7 release today. However, we don't currently run tests in CI againt mypy 1.1.1, so I'm not totally sure this is the case.

Please continue to report any issues you hit with mypy 1.1.1 (whether using pydantic v1 or v2), and I will try to address them as I can. Many of the issues tracked here were actually also issues with earlier versions of mypy and/or required fixes in v2 as well, so it's very helpful.

**Comment by trim21** [comment]
I'm running mypy 1.1.1 with pydantic 1.10.7 in ci， it still failed because of pydantic, I'll create a issue with details later.

**Comment by markedwards** [comment]
This code is still not working with mypy 1.1.1 and pydantic 1.10.7:
```
from pydantic import BaseModel, Field


class Settings(BaseModel):
    foo: str = Field(..., env='foo')


settings = Settings()  # error: Missing named argument "foo" for "Settings"
```

**Comment by dmontagu** [comment]
@markedwards I assume you meant to inherit from `BaseSettings` rather than `BaseModel`.

I think this is going to be impossible to resolve without using the pydantic mypy plugin due to the fact that mypy now respects the `@dataclass_transform` decorator (and this is important for IDE integrations), and this applies to any class that inherits from `BaseModel` (and therefore any class that inherits from `BaseSettings`).

It does appear to be working correctly if you use the pydantic mypy plugin though.

**Comment by dmontagu** [comment]
Okay, actually, it looks like there may be a good solution: you can do
```python
class Settings(BaseModel):
    foo: str = Field(default=..., env='foo')
```
this has the same runtime semantics but the `@dataclass_transform` will think there is a default value. In particular, I don't get mypy errors with the code written like this.

**Comment by markedwards** [comment]
@dmontagu yes, corrected the example.  Actually, you're right it's working okay with the plugin, and with the modification you suggest.  I had thought the plugin was enabled in my environment but it was not.

Thanks.

**Comment by dmontagu** [comment]
Once https://github.com/pydantic/pydantic/pull/5167 is merged, I think we will have addressed all reported issues with pydantic and mypy 1.1.1 (in both v1 and v2).

@trim21 if you are hitting a new bug I'm definitely interested to resolve it, please create an issue and I'll do it as soon as I can.

**Comment by dmontagu** [comment]
I'm going to close this now, though will still note that I won't be surprised if there are issues.

In general, for new versions of mypy, our goal will be to support them in v2 and backport fixes as best we can, but make no promises that we will maintain the integration of pydantic v1 with future mypy versions.
