### ISSUE TITLE
KeyError with validate_call on a function containing type annotations with a list of TypedDict

### ISSUE THREAD

**Issue by diego-pm** [pydantic/pydantic#6380]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

When using the decorator `validate_call` on a function that contains a type annotation of a list of typed dicts, I get a KeyError.

### Example Code

```Python
from pydantic import validate_call
from typing_extensions import TypedDict
from typing import List


class MyDict(TypedDict):
    a: int
    b: str


@validate_call
def foo(c: List[MyDict]):  # KeyError: '__main__.MyDict:13418384'
    pass
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0
        pydantic-core version: 2.0.1 release build profile
                 install path: /home/myuser/miniconda3/envs/myenv/lib/python3.8/site-packages/pydantic
               python version: 3.8.15 (default, Nov  4 2022, 20:59:55)  [GCC 11.2.0]
                     platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.17
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @lig

**Comment by Kludex** [comment]
This is fixed on 61cdaea8817b7bf7421b242fefccd6e092c917ee.

It will be available on the next release. Thank you for the report. 🙏 

As a friendly note, the check mark asks for the user to check against the main branch. 👀

**Comment by diego-pm** [comment]
I installed the latest version with `pip install --upgrade git+https://github.com/pydantic/pydantic.git@main`, but the error still occurs for me.

**Comment by Kludex** [comment]
It's okay. :+1:

That happened cause the version installed was the same as the version we have on main (even if it's on main, we have the same version defined there as the latest release on pypi).
