### ISSUE TITLE
Cannot validate JSON numbers as Decimals with Pydantic 2.0

### ISSUE THREAD

**Issue by larashores** [pydantic/pydantic#6688]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I have a Pydantic model that includes an arbitrary `dict` type. This dict might hold financial data, so I have to be extra careful to not lose any precision due to float types. For example, suppose we have the following JSON.

    {
         "value": {"decimal": 1.39084209843098430984598453098430}
    } 

This should serialize into the following:

    Model(value={'decimal': Decimal('1.39084209843098430984598453098430')})

This can be achieved in Pydantic 1.0 by using `json_dumps`, `json_loads` and the `simplejson` library.

    import pydantic

    class Model(pydantic.BaseModel):
        class Config:
            json_dumps = lambda *args, **kwargs: simplejson.dumps(*args, **kwargs, use_decimal=True)
            json_loads = lambda *args, **kwargs: simplejson.loads(*args, **kwargs, use_decimal=True)
        
        value: dict

However, `json_dumps` and `json_loads` are deprecated in Pydantic 2.0. I can't figure out an alternate way to get this to work. I tried using `model_validator` and `field_validator` to do this, but both parse the JSON into a dict before I have a chance to do it myself.

    import pydantic

    class Model(pydantic.BaseModel):
        value: dict

        @pydantic.model_validator(mode="before")
        def validate_model(cls, data):
            print("Validate Model Data:", repr(data))
            return data

        @pydantic.field_validator("value", mode="before")
        def validate_field(cls, data):
            print("Validate Field Data:", repr(data))
            return data

This prints out the following:

    Validate Model Data: {'value': {'decimal': 1.3908420984309844}}
    Validate Field Data: {'decimal': 1.3908420984309844}

Is there any way to achieve this with the new Pydantic 2.0?

### Affected Components

- [X] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [X] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @Kludex

**Comment by adriangb** [comment]
I'm not sure this is the *best* solution but you can try:

```python
from decimal import Decimal
import json
from typing import Union, List, Dict

from typing_extensions import TypeAliasType
import pydantic


FancyJson = TypeAliasType('FancyJson', Union[List['FancyJson'], Dict[str, 'FancyJson'], Decimal, int, str, bool, int, None])


class Model(pydantic.BaseModel):
    value: FancyJson


print(Model.model_validate_json(json.dumps({'value': {'decimal': 1.3908420984309844}})))
#> value={'decimal': Decimal('1.39084209843098438597053245757706463336944580078125')}
```

**Comment by larashores** [comment]
This still doesn't solve the problem of loss of precision. I can create a JSON string with arbitrary precision, but when it's loaded into pydantic it's converted into a float before getting converted into a Decimal so precision is lost. I guess this isn't unique to `dict` types.

    import decimal
    import pydantic

    class Model(pydantic.BaseModel):
        decimal:  decimal.Decimal

    number = decimal.Decimal("1.39084209843098430984598453098430")
    data = f'{{"decimal": {number}}}'
    model = Model.model_validate_json(data)

    print(data)
    #> value={"decimal": 1.39084209843098430984598453098430}

    print(model.decimal)
    #> value=1.39084209843098438597053245757706463336944580078125')

    print(model.decimal == number)
    #> value=False

**Comment by adriangb** [comment]
Yes we fixed the actual issue now 😀

**Comment by larashores** [comment]
Just tried with the latest 2.1.0 and it still doesn't fix the issue on model validation. Decimal precision is kept on serialization but lost during validation. I can work around this by doing `Model.model_validate(simplejson.loads(data, use_decimal=True)` instead of `Model.model_validate_json(data)` but it's just a bit clunky and error prone. It also makes it difficult to integrate models with decimals into `fastapi` which heavily uses `pydantic`.

Appreciate all the work you're doing though and understand if performance is more important than being strict about the precision 😄

**Comment by adriangb** [comment]
Can you give an example? We added a test that should be equivalent to the bug report in your first post: https://github.com/pydantic/pydantic/blob/3284a249794efc30ec1935a0095671263a175c4e/tests/test_types.py#L5625-L5633. Did we miss something?

**Comment by larashores** [comment]
Ahhh I see this is actually less of an issue for me than I thought. It's only an issue for numbers too big to be held in a double (I think 15 digits). `Decimal`s can hold up to 28 digits. Not the end of the world though. It would be nice to have but I'm happy with how things work now :).

```python
from pydantic import TypeAdapter
from decimal import Decimal

ta = TypeAdapter(Decimal) 
assert ta.validate_json('1.1234567890123456') == Decimal('1.1234567890123456')
```

**Comment by larashores** [comment]
Oh I actually found another difficulty with the current approach. Trailing zeros are lost on validation. This can be an issue if the decimal represents money and they are printed without fixed precision. For example, the following assertion will fail. 

```python
from pydantic import TypeAdapter
from decimal import Decimal

ta = TypeAdapter(Decimal) 
value = ta.validate_json('1.10')
assert value == "1.10", value
# Traceback (most recent call last):
#   File "example.py", line 6, in <module>
#     assert value == "1.10", value
# AssertionError: 1.1
```

**Comment by adriangb** [comment]
What about `value == Decimal(“1.1”)`?

**Comment by larashores** [comment]
Mhm, that works because `Decimal("1.1") == Decimal("1.10")` even though `str(Decimal("1.1")) != str(Decimal("1.10"))`. It can be worked around by explicitly setting the decimal places, eg. `str(TypeAdapter(Decimal).validate_json('1.10').quantize(Decimal("1.00"))) == "1.10"`. Wanted to share difficulties I've been having with the migration though.

**Comment by adriangb** [comment]
I'm not sure what you want us to do. That's not a Pydantic problem:

```python
>>> Decimal('1.10') == '1.10'
False
```

We're basically just calling `Decimal(str(<input>))`.

**Comment by dmontagu** [comment]
@larashores I think this behaves the same in Pydantic v1:
```python
from pydantic import parse_raw_as
from decimal import Decimal

value = parse_raw_as(Decimal, '1.10')
print(value)
#> 1.1

value = parse_raw_as(Decimal, '"1.10"')
print(value)
#> 1.10
```
In v2, if you pass a JSON string, it does do what I think you want it to:
```python
from pydantic import TypeAdapter
from decimal import Decimal

ta = TypeAdapter(Decimal) 
value = ta.validate_json('"1.10"')
assert str(value) == "1.10"
```
I'll note that in principle we may even be able to get `value = ta.validate_json('1.10')` to work properly with this by being more sophisticated with our JSON deserialization into a `Decimal`, but as far as I'm aware that never worked in pydantic v1 and is a non-trivial feature request.

(@davidhewitt for context as I think you were looking at changes to JSON deserialization in the context of `Decimal`)

**Comment by dmontagu** [comment]
Also, @larashores, even though my attempt to reproduce a difference in behavior between v1 and v2 actually convinced me we do the same thing between the two versions, if you can show us an example of code that _does_ behave differently in v1 and v2 (and is better in v1), that would be helpful/a high priority to resolve.
