### ISSUE TITLE
Re-export v1 to v1 module for 1.x

### ISSUE THREAD

**Issue by AngellusMortis** [pydantic/pydantic#6694]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

To help with migrating to v2, I think it would be great to re-export everything in Pydantic 1.10.x into a `v1` module similar to how v2 does. This would allow adding a deprecation notice everywhere on 1.10.x that is not using the v1 module to get projects to migrate to that first.

A great example/use case is that a decent number (5+) Home Assistant integrations use Pydantic to some capacity. They are all maintained by different people and upgrading them all to v2 is going to take some time. If we had a v1.10.12 (or whatver) version of Pydantic that had the API for v1 (`pydantic.v1`) it would make the migration process to v2 much smoother since we get all packages/integrations using v1.10.12 (or whatever) and then we can test everything on v2 (with the v1 interface) so we can get Home Assistant itself on v2 ASAP. That would allow each integration dev to migrate everything else on their own pace.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @dmontagu

**Comment by samuelcolvin** [comment]
We could probably do this with just a clever module `__getattr__`.

**Comment by allenporter** [comment]
To give some numbers behind the home-assistant case it has 31 paths to pydantic: https://gist.github.com/allenporter/ddf327e1130c29f9fe3f494162599c5b likely ~20% of them have been updated so far by engaged contributors subscribed or liking this issue.

**Comment by sodul** [comment]
I would love to see this. I'm dealing with dozens of Pydantic enabled modules in our internal codebase and since I do not want to break the tools between our development branches and our release branches I will have to resort to update all imports with a pattern like such:
```python
import pedantic
if pydantic.__version__.startswith('1.'):
    # v1 imports
else:
    # v2 imports
```
If `import pydantic.v1` worked with v1 of Pydantic, I could perform the changes more globally without the need to do conditional imports and be able to refactor the codebase for v2 more smoothly.

**Comment by AngellusMortis** [comment]
`__version__` is deprecated, you are support to [use importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html#overview) now. There is a backport if you are on/supporting an old enough version.

**Comment by sodul** [comment]
Thanks @AngellusMortis, this is what I ended up doing right after our regular imports:
```
try:
     # Forward compatibility with pydantic v2
     import pydantic.v1 as pydantic

     GenericModel = pydantic.BaseModel
     _PYDANTIC_V1 = False
 except ImportError:
     import pydantic  # type: ignore
     # https://docs.pydantic.dev/2.4/concepts/models/#generic-models
     import pydantic.generics as pydantic_generics

     GenericModel = pydantic_generics.GenericModel

     _PYDANTIC_V1 = True
```

This is very temporary since we only need to be backward/forward compatible for a few weeks.

**Comment by sydney-runkle** [comment]
Addressed in https://github.com/pydantic/pydantic/pull/9042

**Comment by AngellusMortis** [comment]
This is not resolved. Only the symbols for `pydantic` are re-imported, none of the sub-modules. 

Works in v2 but breaks in v1.10.15:
```python
from pydantic.v1.color import Color
from pydantic.v1.fields import ModelField
```
