### ISSUE TITLE
Recurse KeyError when using several BaseModels 

### ISSUE THREAD

**Issue by hoorelbeke-jimmy** [pydantic/pydantic#7611]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The following code is working well with pydantic 2.3, but after upgrading it to 2.4 it fails with the following error:

```bash
Traceback (most recent call last):
  File "/home/ahoorelbeke/generator_v1_detailed/src/generator_source/parameters/parameters_equipment_design.py", line 23, in <module>
    class E(BaseModel):
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 184, in __new__
    complete_model_class(
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 495, in complete_model_class
    schema = apply_discriminators(simplify_schema_references(schema))
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 519, in simplify_schema_references
    schema = walk_core_schema(schema, count_refs)
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 439, in walk_core_schema
    return f(schema, _dispatch)
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 515, in count_refs
    recurse(state['definitions'][ref], count_refs)
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 215, in walk
    return f(schema, self._walk)
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 503, in count_refs
    return recurse(s, count_refs)
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 218, in _walk
    schema = self._schema_type_to_method[schema['type']](schema, f)
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 227, in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 215, in walk
    return f(schema, self._walk)
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 503, in count_refs
    return recurse(s, count_refs)
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 218, in _walk
    schema = self._schema_type_to_method[schema['type']](schema, f)
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 362, in handle_model_fields_schema
    replaced_field['schema'] = self.walk(v['schema'], f)
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 215, in walk
    return f(schema, self._walk)
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 515, in count_refs
    recurse(state['definitions'][ref], count_refs)
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 218, in _walk
    schema = self._schema_type_to_method[schema['type']](schema, f)
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 227, in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 215, in walk
    return f(schema, self._walk)
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 503, in count_refs
    return recurse(s, count_refs)
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 218, in _walk
    schema = self._schema_type_to_method[schema['type']](schema, f)
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 362, in handle_model_fields_schema
    replaced_field['schema'] = self.walk(v['schema'], f)
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 215, in walk
    return f(schema, self._walk)
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 503, in count_refs
    return recurse(s, count_refs)
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 218, in _walk
    schema = self._schema_type_to_method[schema['type']](schema, f)
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 227, in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 215, in walk
    return f(schema, self._walk)
  File "/home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 515, in count_refs
    recurse(state['definitions'][ref], count_refs)
KeyError: '__main__.B:94275587272912'
```

### Example Code

```Python
from pydantic import BaseModel


class A(BaseModel):
    a: int = None


class B(BaseModel):
    a_1: A = None
    a_2: A = None


class C(BaseModel):
    a: A = None
    b: B = None


class D(BaseModel):
    c_1: C = None
    c_2: C = None


class E(BaseModel):
    c: C
```

### Python, Pydantic & OS Version

```Text
        pydantic version: 2.4.0
        pydantic-core version: 2.10.0
          pydantic-core build: profile=release pgo=true
                 install path: /home/ahoorelbeke/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
                     platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: typing_extensions-4.7.1
```

**Comment by davidhewitt** [comment]
Also reported in https://github.com/pydantic/pydantic/pull/7523#issuecomment-1734117331

**Comment by lig** [comment]
I've managed to simplify example a bit

```py
from pydantic import BaseModel


class A(BaseModel):
    pass


class B(BaseModel):
    a_1: A = None
    a_2: A = None


class C(BaseModel):
    b: B = None


class D(BaseModel):
    c_1: C = None
    c_2: C = None


class E(BaseModel):
    c: C
```

Removing any attr in the example above makes code pass

**Comment by Fokko** [comment]
We're seeing this as well at PyIceberg: https://github.com/pola-rs/polars/pull/11312

**Comment by adriangb** [comment]
This should be fixed on `main` now (38bc2da1a68a71c9f36c61c000bb95ebc77764ef). @hoorelbeke-jimmy, @Fokko could you try installing from `main` and see if it fixes things?

**Comment by Fokko** [comment]
Still seeing issues: https://github.com/apache/iceberg/pull/8646

```
tests/conftest.py:58: in <module>
    from pyiceberg.catalog import Catalog
pyiceberg/catalog/__init__.py:42: in <module>
    from pyiceberg.serializers import ToOutputFile
pyiceberg/serializers.py:25: in <module>
    from pyiceberg.table.metadata import TableMetadata, TableMetadataUtil
pyiceberg/table/__init__.py:71: in <module>
    from pyiceberg.table.metadata import INITIAL_SEQUENCE_NUMBER, TableMetadata
pyiceberg/table/metadata.py:419: in <module>
    class TableMetadataWrapper(IcebergRootModel[TableMetadata]):
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/main.py:679: in __class_getitem__
    submodel = _generics.create_generic_submodel(model_name, origin, args, params)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_generics.py:142: in create_generic_submodel
    created_model = meta(
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py:184: in __new__
    complete_model_class(
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py:495: in complete_model_class
    schema = apply_discriminators(simplify_schema_references(schema))
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:481: in simplify_schema_references
    schema = walk_core_schema(schema, count_refs)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:433: in walk_core_schema
    return f(schema.copy(), _dispatch)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:477: in count_refs
    recurse(definitions[ref], count_refs)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:209: in walk
    return f(schema, self._walk)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:465: in count_refs
    return recurse(s, count_refs)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:212: in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:221: in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:209: in walk
    return f(schema, self._walk)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:465: in count_refs
    return recurse(s, count_refs)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:212: in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:324: in handle_tagged_union_schema
    new_choices[k] = v if isinstance(v, (str, int)) else self.walk(v, f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:209: in walk
    return f(schema, self._walk)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:477: in count_refs
    recurse(definitions[ref], count_refs)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:212: in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:221: in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:209: in walk
    return f(schema, self._walk)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:465: in count_refs
    return recurse(s, count_refs)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:212: in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:221: in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:209: in walk
    return f(schema, self._walk)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:465: in count_refs
    return recurse(s, count_refs)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:212: in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:221: in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:209: in walk
    return f(schema, self._walk)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:465: in count_refs
    return recurse(s, count_refs)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:212: in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:221: in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:209: in walk
    return f(schema, self._walk)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:465: in count_refs
    return recurse(s, count_refs)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:212: in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:221: in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:209: in walk
    return f(schema, self._walk)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:465: in count_refs
    return recurse(s, count_refs)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:212: in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:221: in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:209: in walk
    return f(schema, self._walk)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:465: in count_refs
    return recurse(s, count_refs)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:212: in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:221: in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:209: in walk
    return f(schema, self._walk)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:465: in count_refs
    return recurse(s, count_refs)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:212: in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:356: in handle_model_fields_schema
    replaced_field['schema'] = self.walk(v['schema'], f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:209: in walk
    return f(schema, self._walk)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:465: in count_refs
    return recurse(s, count_refs)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:212: in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:221: in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:209: in walk
    return f(schema, self._walk)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:465: in count_refs
    return recurse(s, count_refs)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:212: in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:256: in handle_list_schema
    schema['items_schema'] = self.walk(items_schema, f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:209: in walk
    return f(schema, self._walk)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:477: in count_refs
    recurse(definitions[ref], count_refs)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:212: in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:221: in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:209: in walk
    return f(schema, self._walk)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:465: in count_refs
    return recurse(s, count_refs)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:212: in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:221: in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:209: in walk
    return f(schema, self._walk)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:465: in count_refs
    return recurse(s, count_refs)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:212: in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:356: in handle_model_fields_schema
    replaced_field['schema'] = self.walk(v['schema'], f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:209: in walk
    return f(schema, self._walk)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:465: in count_refs
    return recurse(s, count_refs)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:212: in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:221: in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:209: in walk
    return f(schema, self._walk)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:465: in count_refs
    return recurse(s, count_refs)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:212: in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:283: in handle_tuple_variable_schema
    schema['items_schema'] = self.walk(items_schema, f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:209: in walk
    return f(schema, self._walk)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:477: in count_refs
    recurse(definitions[ref], count_refs)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:212: in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:221: in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:209: in walk
    return f(schema, self._walk)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:465: in count_refs
    return recurse(s, count_refs)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:212: in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:221: in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:209: in walk
    return f(schema, self._walk)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:465: in count_refs
    return recurse(s, count_refs)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:212: in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:356: in handle_model_fields_schema
    replaced_field['schema'] = self.walk(v['schema'], f)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:209: in walk
    return f(schema, self._walk)
../../../../.cache/pypoetry/virtualenvs/pyiceberg-C6VdKk4a-py3.9/lib/python3.9/site-packages/pydantic/_internal/_core_utils.py:477: in count_refs
    recurse(definitions[ref], count_refs)
E   KeyError: 'pyiceberg.types.IcebergType:[944](https://github.com/apache/iceberg/actions/runs/6309187940/job/17128641305?pr=8647#step:7:945)05463474192'
make: *** [Makefile:67: test-coverage] Error 4
```

The line numbers have changed, so it looks like it is installing the latest version. @hoorelbeke-jimmy any success on your end?

**Comment by hoorelbeke-jimmy** [comment]
> This should be fixed on `main` now ([38bc2da](https://github.com/pydantic/pydantic/commit/38bc2da1a68a71c9f36c61c000bb95ebc77764ef)). @hoorelbeke-jimmy, @Fokko could you try installing from `main` and see if it fixes things?

My snippet works when installing pydantic from `main`

**Comment by kefahi** [comment]
I, too, confirm still facing the same issue in my code and that running off the `main` branch solves it.
```bash
pip uninstall pydantic
pip install -U git+https://github.com/pydantic/pydantic.git@main
```

**Comment by davidhewitt** [comment]
We are planning to release v2.4.1 with the current fix on `main` and then investigate further the iceberg case above. Hopefully this mitigates the issue for the majority of folks.

**Comment by adriangb** [comment]
> Still seeing issues: https://github.com/apache/iceberg/pull/8646

I'm going to take a look at this.

**Comment by Fokko** [comment]
Appreciate it, let me know if there is anything I can help with

**Comment by kefahi** [comment]
I also verified now from my end.

2.4.1 works flawlessly!

:heart_eyes: 

Thanks!

**Comment by nmichlo** [comment]
This still seems broken for me in v2.4.1

**Comment by adriangb** [comment]
@nmichlo can you try `main` (or 2.4.2 once it comes out)?

**Comment by nmichlo** [comment]
v2.4.2 is working @adriangb, thank you!
