### ISSUE TITLE
Unexpected behaviour using a custom validator with `mode='wrap'` when used with `model_validate_json`

### ISSUE THREAD

**Issue by thusithaC** [pydantic/pydantic#8147]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

We would like to to use a custom `wrap`mode  model_validator to collect and organize validation errors thrown by some models. 

I followed the pattern for `mode='wrap'` model validator as discussed in https://github.com/pydantic/pydantic/discussions/7470#discussioncomment-7028695 given that I could not find any documentation on how to use the wrap mode correctly. 

I got a peculiar behaviour when using the custom validator with `model_validate_json` having an UUID field. 
in short, if I use a wrap mode model validator, uuid fields seem to throw a validation error if used in strict mode (which it should not according to the documentation) .

Running the below code yields:
```
2.5.0
1 validation error for MyModelCustomValidator
id
  Input should be an instance of UUID [type=is_instance_of, input_value='af623f6d-ea8c-41ab-9000-43ff15eb832c', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/is_instance_of
1 validation error for MyModel
id
  Input should be an instance of UUID [type=is_instance_of, input_value='af623f6d-ea8c-41ab-9000-43ff15eb832c', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/is_instance_of
1 validation error for MyModelCustomValidator
id
  Input should be an instance of UUID [type=is_instance_of, input_value='af623f6d-ea8c-41ab-9000-43ff15eb832c', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/is_instance_of
```

Shouldn't the `MyModelCustomValidator` be identical to `MyModel`? i.e. why is it throwing a uuid validation error when for 
`model_validate_json` ? 

### Example Code

```Python
import pydantic
from pydantic import BaseModel, ConfigDict, model_validator, ValidationError
from uuid import uuid4, UUID
import json

print(pydantic.__version__)


class MyModel(BaseModel):
    """Model with a UUID."""
    model_config = ConfigDict(from_attributes=True, frozen=True)

    id: UUID
    name: str


class MyModelCustomValidator(MyModel):

    @model_validator(mode="wrap")
    def validate_model(self, handler):
        """Wrap validator."""
        validated_self, validation_errors = None, []
        try:
            validated_self = handler(self)
        except ValidationError as e:
            validation_errors = e.errors()
        if validation_errors:
            raise ValidationError.from_exception_data(
                title=self.__class__.__name__, line_errors=validation_errors
            )
        return validated_self


if __name__ == "__main__":
    uuid_val = uuid4()
    uuid_val_str = str(uuid_val)

    obj_json = {
        "id": uuid_val_str,
        "name": "test_with_uuid_obj"
    }

    obj = {
        "id": uuid_val,
        "name": "test_with_uuid_obj"
    }

    # 1.a
    # this should work, uuid as string is allowed in strict mode for model_validate_json
    instance_my_model = MyModel.model_validate_json(json.dumps(obj_json), strict=True)
    assert isinstance(instance_my_model, MyModel)

    # 1.b
    # this should also work, same as 1.a, but using the wrap model_validator
    # however it throws a validation error
    try:
        _ = MyModelCustomValidator.model_validate_json(json.dumps(obj_json), strict=True)
    except ValidationError as e:
        print(e)

    # 2.a Works as expected
    _ = MyModel.model_validate(obj, strict=True)
    # 2.b Works as expected
    _ = MyModelCustomValidator.model_validate(obj, strict=True)

    # 2.c Works correctly by throwing an error
    try:
        _ = MyModel.model_validate(obj_json, strict=True)
    except ValidationError as e:
        print(e)

    # 2.d Works correctly by throwing an error
    try:
        _ = MyModelCustomValidator.model_validate(obj_json, strict=True)
    except ValidationError as e:
        print(e)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.0
        pydantic-core version: 2.14.1
          pydantic-core build: profile=release pgo=true
                 install path: /Users/s125294/work/ambiata/lmui/backend/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)]
                     platform: macOS-14.1-arm64-arm-64bit
             related packages: typing_extensions-4.8.0 pydantic-settings-2.0.3 fastapi-0.104.1 mypy-1.7.0 email-validator-2.1.0.post1
```

**Comment by davidhewitt** [comment]
Thanks for the report; should be fixed by https://github.com/pydantic/pydantic-core/pull/1080

**Comment by thusithaC** [comment]
Thank you very much!

**Comment by andrewVolodko** [comment]
It seems like the issue still reproduces, but with StrEnum 

```
obj = {
        "status": "completed"
    }
```



```
class StatusResponse(JsonBaseModel):
    status: Status
```

```
class Status(StrEnum):
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
```

```
class JsonBaseModel(BaseModel):
    model_config = ConfigDict(populate_by_name=True, strict=True)

    @model_validator(mode="wrap")
    def log_failed_validation(self, handler: ModelWrapValidatorHandler[Self]) -> Self:
        try:
            return handler(self)
        except ValidationError:
            # Logging
            raise
```

Code: 
`StatusResponse.model_validate_json(json.dumps(obj)`


If `log_failed_validation` method presented in `JsonBaseModel`, `pydantic` always raises exception `Input should be an instance of Status`, even though the value is the same.

FYI: I've already tried `use_enum_values=True` parameter in `ConfigDict`
