### ISSUE TITLE
ImportError: cannot import name 'PydanticUndefined' from 'pydantic_core' (unknown location)

### ISSUE THREAD

**Issue by edgBR** [pydantic/pydantic#8429]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Seems that scikit learn CI pipeline broke to the new update:

https://github.com/scikit-learn/scikit-learn/issues/28004

### Example Code

```Python
Traceback (most recent call last):
  File "/usr/share/miniconda/bin/conda-lock", line 6, in <module>
    from conda_lock import main
  File "/usr/share/miniconda/lib/python3.11/site-packages/conda_lock/__init__.py", line 3, in <module>
    from conda_lock.conda_lock import main
  File "/usr/share/miniconda/lib/python3.11/site-packages/conda_lock/conda_lock.py", line 50, in <module>
    from conda_lock.conda_solver import solve_conda
  File "/usr/share/miniconda/lib/python3.11/site-packages/conda_lock/conda_solver.py", line 20, in <module>
    from conda_lock.invoke_conda import (
  File "/usr/share/miniconda/lib/python3.11/site-packages/conda_lock/invoke_conda.py", line 15, in <module>
    from conda_lock.models.channel import Channel
  File "/usr/share/miniconda/lib/python3.11/site-packages/conda_lock/models/__init__.py", line 1, in <module>
    from pydantic import BaseModel
  File "/usr/share/miniconda/lib/python3.11/site-packages/pydantic/__init__.py", line 372, in __getattr__
    module = import_module(module_name, package=package)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/lib/python3.11/site-packages/pydantic/main.py", line 13, in <module>
    from pydantic_core import PydanticUndefined
ImportError: cannot import name 'PydanticUndefined' from 'pydantic_core' (unknown location)
```

### Python, Pydantic & OS Version

```Text
pydantic-core-2.14.6
pydantic-2.5.3
```

**Comment by hramezani** [comment]
Thanks @edgBR for reporting this.

AFAIK, There is no change in related to `PydanticUndefined` in `pydantic` and `pydantic-core`.

I've tried the `from pydantic_core import PydanticUndefined` in a fresh env with `pydantic-core-2.14.6` and `pydantic-2.5.3` and it was OK.

**Comment by samuelcolvin** [comment]
I too am able to run `from pydantic_core import PydanticUndefined` fine with 2.5.3.

@edgBR it looks like you're installing from conda-forge, is that right? I don't know how, but maybe that's part of the problem.

The "(unknown location)" makes me think this could be an issue with pydantic-core not working at all in that environment, and the above import is just the first pydantic_core import that's being hit.

**Comment by Timo1104** [comment]
I have noticed the same issue. For us, it occurs only when installing `pydantic` through `conda-forge` on a CI pipelines running linux (windows and macOS pipelines do not suffer from this issue).

For us, a temporary (dirty) fix is to move `pydantic` from the conda dependencies to pip dependencies.

Hopefully this helps in resolving the issue!

**Comment by samuelcolvin** [comment]
I've created https://github.com/conda-forge/pydantic-core-feedstock/issues/79 in the help someone from anaconda can help.

**Comment by edgBR** [comment]
Thanks!

Lets see if the fix it soon!

BR
E

**Comment by waterbug** [comment]
Any news?  I'm trying to build a new image for my app and it's dead in the water ... I assume that the same is true for any app that depends on pydantic ...

**Comment by samuelcolvin** [comment]
Well, it's specific to condaforge as far as we know (please confirm if that's NOT the case) and pydantic 2.5.3.

That likely means <1% of those using Pydantic are affected, not any app that depends on Pydantic.

**Comment by d-chambers** [comment]
A user just ran into this as well in a scientific library we maintain (https://github.com/DASDAE/dascore/issues/325). 

When pydantic is installed with conda on python 3.12, like this:

```bash
conda create -c conda-forge -n pydantic pydantic
conda activate pydantic
```

Trying to import the `PlainValidtor` like this:

```python
from pydantic import PlainValidator
```

raises this Error:

```bash
  File "<string>", line 1, in <module>
  File "/home/derrick/anaconda3/envs/pydantic/lib/python3.12/site-packages/pydantic/__init__.py", line 363, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/derrick/anaconda3/envs/pydantic/lib/python3.12/site-packages/pydantic/_migration.py", line 278, in wrapper
    from ._internal._validators import import_string
  File "/home/derrick/anaconda3/envs/pydantic/lib/python3.12/site-packages/pydantic/_internal/_validators.py", line 14, in <module>
    from pydantic_core import PydanticCustomError, core_schema
ImportError: cannot import name 'PydanticCustomError' from 'pydantic_core' (unknown location)
```

However,  if I create a new environment then install pydantic with pip it works fine:

```bash
conda create -n py312 python=3.12
conda activate py312
python -m pip install pydantic
```

In the broken environment that installed pydantic with conda uninstalling then re-installing `pydantic_core` with pip fixes the issue.

Here is the output of the pydantic version command for both environments:

## broken environment (pydantic)
pydantic version: 2.5.3
pydantic-core version: 2.14.6
pydantic-core build: profile=release pgo=false
install path: /home/derrick/anaconda3/envs/pydantic/lib/python3.12/site-packages/pydantic
python version: 3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:43:22) [GCC 12.3.0]
platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.31
related packages: typing_extensions-4.9.0

## working environment (py312)
pydantic version: 2.5.3
pydantic-core version: 2.14.6
pydantic-core build: profile=release pgo=true
install path: /home/derrick/anaconda3/envs/py312/lib/python3.12/site-packages/pydantic
python version: 3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:43:22) [GCC 12.3.0]
platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.31
related packages: typing_extensions-4.9.0

The difference I note is that in the working environment pgo=true whereas in the broken environment pgo=false. I don't know what that means though.

**Comment by d-chambers** [comment]
> That likely means <1% of those using Pydantic are affected, not any app that depends on Pydantic.

This is probably true, but it also means anyone using conda to install any library that depends on pydantic will probably end up with a broken installation, so not an insignificant number of folks.

**Comment by waterbug** [comment]
Oh well, my app's dependency on pydantic was through the "inflect" module which turned out to be some cruft so I removed it ... no worries for me, sorry for the noise.

**Comment by xhochy** [comment]
This has been solved in conda-forge and new installs in 15min from now will no longer be affected.

**Comment by samuelcolvin** [comment]
Great, thanks so much for your help on this @xhochy.

I'll close this assuming it's now fixed, if anyone continues to experience the problem, please let us know.

**Comment by edgBR** [comment]
Hi,

Im still having the same problem, scikit learn CI is still broken:

https://dev.azure.com/scikit-learn/scikit-learn/_build/results?buildId=61825&view=logs&j=dde5042c-7464-5d47-9507-31bdd2ee0a3a&t=7d852497-2547-55fa-986f-0b436c028d7e

**Comment by WangYao-GoGoGo** [comment]
> A user just ran into this as well in a scientific library we maintain ([DASDAE/dascore#325](https://github.com/DASDAE/dascore/issues/325)).
> 
> When pydantic is installed with conda on python 3.12, like this:
> 
> ```shell
> conda create -c conda-forge -n pydantic pydantic
> conda activate pydantic
> ```
> 
> Trying to import the `PlainValidtor` like this:
> 
> ```python
> from pydantic import PlainValidator
> ```
> 
> raises this Error:
> 
> ```shell
>   File "<string>", line 1, in <module>
>   File "/home/derrick/anaconda3/envs/pydantic/lib/python3.12/site-packages/pydantic/__init__.py", line 363, in __getattr__
>     return _getattr_migration(attr_name)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/derrick/anaconda3/envs/pydantic/lib/python3.12/site-packages/pydantic/_migration.py", line 278, in wrapper
>     from ._internal._validators import import_string
>   File "/home/derrick/anaconda3/envs/pydantic/lib/python3.12/site-packages/pydantic/_internal/_validators.py", line 14, in <module>
>     from pydantic_core import PydanticCustomError, core_schema
> ImportError: cannot import name 'PydanticCustomError' from 'pydantic_core' (unknown location)
> ```
> 
> However, if I create a new environment then install pydantic with pip it works fine:
> 
> ```shell
> conda create -n py312 python=3.12
> conda activate py312
> python -m pip install pydantic
> ```
> 
> In the broken environment that installed pydantic with conda uninstalling then re-installing `pydantic_core` with pip fixes the issue.
> 
> Here is the output of the pydantic version command for both environments:
> 
> ## broken environment (pydantic)
> pydantic version: 2.5.3 pydantic-core version: 2.14.6 pydantic-core build: profile=release pgo=false install path: /home/derrick/anaconda3/envs/pydantic/lib/python3.12/site-packages/pydantic python version: 3.12.0 | packaged by conda-forge | (main, Oct 3 2023, 08:43:22) [GCC 12.3.0] platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.31 related packages: typing_extensions-4.9.0
> 
> ## working environment (py312)
> pydantic version: 2.5.3 pydantic-core version: 2.14.6 pydantic-core build: profile=release pgo=true install path: /home/derrick/anaconda3/envs/py312/lib/python3.12/site-packages/pydantic python version: 3.12.0 | packaged by conda-forge | (main, Oct 3 2023, 08:43:22) [GCC 12.3.0] platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.31 related packages: typing_extensions-4.9.0
> 
> The difference I note is that in the working environment pgo=true whereas in the broken environment pgo=false. I don't know what that means though.

It works.
