### ISSUE TITLE
KeyError when trying to instantiate BaseModels that depend on each other

### ISSUE THREAD

**Issue by arthur-encord** [pydantic/pydantic#9887]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am running into this particular issue that uses generics and 2 base models that depend on each other. I would expect the example below to work, but I am unable to instantiate both `AndCondition` and `OrCondition`, I get a key error:
`KeyError: '__main__.AndCondition:4375113792[int:4324167992]'`

Interestingly, when running this code in a jupyter notebook, it fails the first time, but succeeds the second time.

### Example Code

```Python
from typing import Generic, TypeVar

from pydantic import BaseModel

LeafType = TypeVar("LeafType")


class AndCondition(BaseModel, Generic[LeafType]):
    and_conditions: list["LeafType | AndCondition | OrCondition"]


class OrCondition(BaseModel, Generic[LeafType]):
    or_conditions: list["LeafType | OrCondition | AndCondition"]


AndCondition[int](and_conditions=[1, 2])
OrCondition[int](or_conditions=[3, 4])
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.1
        pydantic-core version: 2.18.2
          pydantic-core build: profile=release pgo=true
               python version: 3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-14.5-arm64-arm-64bit
             related packages: pyright-1.1.358 typing_extensions-4.8.0 mypy-1.8.0 fastapi-0.111.0
                       commit: unknown
```
```

**Comment by Viicos** [comment]
Could you try on 2.8? Seems like it was fixed there.

**Comment by arthur-encord** [comment]
I just tried with `2.8.2` and can still reproduce the issue, yes

**Comment by sydney-runkle** [comment]
Can confirm I'm getting the issue on v2.8.2 as well. Thanks for the bug report @arthur-encord!

Maybe this is related to https://github.com/pydantic/pydantic/issues/9319, based on the nature of the error...

**Comment by arthur-encord** [comment]
Hi @sydney-runkle! Was checking with the new version and I think it's still occurring? Trying to run this snippet with pydantic 2.9.2:

```
from typing import Generic, TypeVar

from pydantic import BaseModel, version

LeafType = TypeVar("LeafType")
print(version.version_info())


class AndCondition(BaseModel, Generic[LeafType]):
    and_conditions: list["LeafType | AndCondition | OrCondition"]


class OrCondition(BaseModel, Generic[LeafType]):
    or_conditions: list["LeafType | OrCondition | AndCondition"]


AndCondition[int](and_conditions=[1, 2])
OrCondition[int](or_conditions=[3, 4])
```

And still getting a KeyError:

```
             pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
               python version: 3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-15.0-arm64-arm-64bit
             related packages: pyright-1.1.358 mypy-1.11.0 typing_extensions-4.12.2 fastapi-0.111.1

...
KeyError: '__main__.AndCondition:4400097808[int:4381856056]'
```

**Comment by Viicos** [comment]
The proposed fix (https://github.com/pydantic/pydantic/commit/f70db7fadcfa69458c74724d6aa3ae6b435905a5) in https://github.com/pydantic/pydantic/issues/10279 fixes it (see https://github.com/pydantic/pydantic/issues/10279#issuecomment-2382846088). However, there's another issue happening here.

When `AndCondition` (or `OrCondition`) is parametrized with the type `int`, Pydantic will parametrize the annotation for the `and_conditions` field (see [`_generics.replace_types`](https://github.com/pydantic/pydantic/blob/01b59297ef840d16049f125a8b0abef9fe0c991f/pydantic/_internal/_generics.py#L252)). In theory:

```python
list["LeafType | AndCondition | OrCondition"]
```

should become:

```python
list[int | AndCondition | OrCondition]
```

but because `AndCondition` and `OrCondition` are defined as generics with the same `LeafType`, Pydantic wrongfully assume they were explicitly parametrized with the `LeafType` type var in the annotation. Thus, it ends up transforming the annotation to:

```python
list[int | AndCondition[int] | OrCondition[int]]
```

Which is incorrect and should only be done if the following field annotation was used:

```python
and_conditions: list["LeafType | AndCondition[LeafType] | OrCondition[LeafType]"]
```

This means that currently, the following will not validate, even though it is correct from a type checking perspective:

```python
OrCondition[int](or_conditions=[AndCondition(and_conditions=[""])])
```

---

I don't how hard it will be to correct the generic logic currently in place. As a partial workaround that is working on 2.9:

```python
from typing import Generic, TypeVar

from pydantic import BaseModel

LeafType1 = TypeVar("LeafType1")
LeafType2 = TypeVar("LeafType2")


class AndCondition(BaseModel, Generic[LeafType1]):
    and_conditions: list["LeafType1 | AndCondition | OrCondition"]


class OrCondition(BaseModel, Generic[LeafType2]):
    or_conditions: list["LeafType2 | OrCondition | AndCondition"]

OrCondition[int](or_conditions=[AndCondition(and_conditions=[""])])  # works as expected
OrCondition[int](or_conditions=[OrCondition(or_conditions=[""])])  # does not work
```

**Comment by Viicos** [comment]
Alternatively, I would recommend explicitly parametrizing models in the annotations. If

```python
OrCondition[int](or_conditions=[AndCondition(and_conditions=[""])])
```

is expected to work, then I would suggest defining your models this way:

```python

class AndCondition(BaseModel, Generic[LeafType]):
    and_conditions: list["LeafType | AndCondition[Any] | OrCondition[Any]"]


class OrCondition(BaseModel, Generic[LeafType]):
    or_conditions: list["LeafType | OrCondition[Any] | AndCondition[Any]"]

```

**Comment by Viicos** [comment]
The `KeyError` will be fixed by https://github.com/pydantic/pydantic/pull/10704, and I opened https://github.com/pydantic/pydantic/issues/11223 for the remaining issue.
